### PR TITLE
Added kwargs and type hints for better autocomplete

### PR DESCRIPTION
**Pull request by jfloyd1697**

### CODE REVIEW

**Comment by xy3** [comment]
@jfloyd1697 Nice, but `_typeshed` doesn't exist at runtime so the tests fail

**Comment by jfloyd1697** [comment]
Fixed

**Comment by xy3** [comment]
Just linting now @jfloyd1697

**Comment by jfloyd1697** [comment]
Also added aliases to dicts for short hand

**Review by xy3 — APPROVED** [review]

**Pull request merged**
